### ISSUE TITLE
"@" instead of "this."

### ISSUE THREAD

**Issue by yegor256** [yegor256/eo#10]
How about we use `@` sign in front of attribute names instead of `this.` (like in Java)? Sounds practical to me. This is how Ruby works.

**Comment by MonsieurLuge** [comment]
Is this keyword really usefull ?

I mean, if all the properties owned by the object are private and immutable, why should we add this keyword to access these properties ?

Same for the methods.

**Comment by mdbs99** [comment]
@MonsieurLuge 
Using a prefix like `@` turns the code more readable.
But, I agree, if we want we can cut both (this and `@`) defining a pattern: All variable created inside the constructor, will be attributes. The only problem is a colision names between arguments and attributes.

**Comment by yegor256** [comment]
@MonsieurLuge well, but what about method arguments? We have to distinguish them somehow from attributes:

```
Integer {
  int @value;
  void add(int value) {
    @value += value;
  }
}
```

See?

**Comment by MonsieurLuge** [comment]
Of course, but in many case it's just a naming convention issue.

"@" reminds me annotations. But, i agree that it's a very short way to see where are the object's properties.

If you want to keep a keyword, why not "self" ? The object is composed by its internal properties so the "self" keyword sounds better for me in an object oriented context.

**Comment by mdbs99** [comment]
I like the word, `self` — because Object Pascal — but this isn't good. The same for `this`.
Sometimes developers will write `self.value`, sometimes not (because the argument name is just `v`). This is a inconsistence.

IMO It's better to use only one way, one style.

**Comment by yegor256** [comment]
@mdbs99 I also like `@` notation. It's explicit and can't be skipped.

**Comment by yegor256** [comment]
pull request is here: #18 If there are no strong objectives, I will merge it

**Comment by yegor256** [comment]
no objectives, merged :)
