### ISSUE TITLE
JavaClass.java:43-45: Java class method generator is not imple...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/eo#105]
The puzzle `95-977c9f11` in `eo-compiler/src/main/java/org/eolang/compiler/java/JavaClass.java` (lines 43-45) has to be resolved: Java class method generator is not implemented. We may pass collection of methods as `JavaClass` constructor arguments. All methods should be public.

The [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) was created by Kirill on 10-Jan-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0pdd** [comment]
@yegor256 please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `95-977c9f11` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/eo#105` was not in scope

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#131](https://github.com/yegor256/eo/issues/131) is solved here.
