### ISSUE TITLE
Object.java:42-44: Object name should be optional. As descr...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/eo#106]
The puzzle `95-fabf1b89` in `eo-compiler/src/main/java/org/eolang/compiler/syntax/Object.java` (lines 42-44) has to be resolved: Object name should be optional. As described in #54, object can be anonymous. I think we should generate some java class name in this case.

The [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) was created by Kirill on 10-Jan-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0pdd** [comment]
@yegor256 please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `95-fabf1b89` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/eo#106` is not assigned, can't get performer
