### ISSUE TITLE
The Javadoc comments are mostly redundant noise.

### ISSUE THREAD

**Issue by pa9ey** [yegor256/eo#107]
I'm particularly talking about the method and attribute comments.

* They are mostly just repeating the code so they add nothing.
* I assume we're not actually going to publish them either.
* They actually clutter and lengthen the file making it harder to mentally process, not easier.
* Qulice cannot guarantee that the comments are actually good so review is still required anyway.

I propose not having them. If the classes are short and to the point and everything is well-named I don't think they will be needed at all. Also, if we have terse, spec-like, well-written tests then usage of the class will also be documented.

Maybe we could keep the class comments to give a brief overview of what the class represents.

If the occasional method is long or tricky to understand then this can be caught in review and comments can be added inside the method.

**Comment by MonsieurLuge** [comment]
I totally agree with you !

**Comment by yegor256** [comment]
@pa9ey I think I agree with you, but this problem has to be submitted to Qulice repository: https://github.com/teamed/qulice
