### ISSUE TITLE
Qulice incorrectly requires that the license text is in a Javadoc comment.

### ISSUE THREAD

**Issue by pa9ey** [yegor256/eo#109]
IntelliJ shows a warning for me, in all the files that have license text. It complains that it is a dangling comment.

Javadoc comments should be attached to classes, methods or attributes, anything else is "dangling".

There is no need for this comment to be anything other than a normal block comment. I suggest we remove whatever rule there is in Qulice that doesn't allow the normal block comment.

**Comment by alex-semenyuk** [comment]
It makes sense for me, since I use Idea too. So the main thing from this discuss http://stackoverflow.com/questions/26075364/comment-style-for-license-headers-in-java , 
that there is no single standard for this, but the recommendation is to use block comments.

**Comment by yegor256** [comment]
@pa9ey makes sense, but you have to submit this problem to qulice repository: https://github.com/teamed/qulice
