### ISSUE TITLE
Types and "New" Objects

### ISSUE THREAD

**Issue by pa9ey** [yegor256/eo#11]
I'm confused about types and about creating objects and the "Hello, World" example.

```
import org.eolang.printed;
import org.eolang.string;
cli(
  printed(
    string("Hello, world!")
  )
)
```

If `string` is the name of the object (see comments [here](https://github.com/yegor256/eo/commit/b9450bc26c3ac2c146a01505cec10ef4e6e4b14b)) how does the compiler know what type it is?
And the same question for `cli` and `printed`.

**EDIT:**
- `string` must be the name of an object, presumably of type `String`, that is created in `org.eolang`.
- The fact that we're passing in an argument means that we're actually constructing a new object by copying the existing one.
- In a similar way `printed` must already exist as an object. (I'm unsure what `cli` is exactly.)

**Comment by SilasReinagel** [comment]
It would appear that the compiler would know the type based on the Type definition in `org.eolang.string`. `string("Hello, world!")` is a call to the object's constructor.

**Comment by pa9ey** [comment]
So there's already an object called `string`?

So is this also a valid program?

```
import org.eolang.printed;
import org.eolang.string;
cli(
  printed(
    string
  )
)
```

What would it do?

**Comment by SilasReinagel** [comment]
That would not be a valid program. You have to construct a `string` object before using it. You construct an object by naming the type of object and passing in any constructor args.

`string("Bond, James Bond")` is equivalent to `"James Bond"` or `new String("James Bond")` in Java.  

`cli(printed(string("")))` would be legal.
`cli(printed(string("Hello, world!")))` would be legal.
`cli(printed(string()))` would not be legal. (no input args. objects always encapsulate something)
`cli(printed(string))` would not be legal. (no string is being constructed)

**Comment by pa9ey** [comment]
"You construct an object by naming the type of object and passing in any constructor args."

But isn't the type `String`? (See comment [here](https://github.com/yegor256/eo/commit/b9450bc26c3ac2c146a01505cec10ef4e6e4b14b).)

(Sorry. I'm probably missing something.)

**Comment by SilasReinagel** [comment]
That might just be a Typo. I don't know whether it will ultimately be `string`or `String`, or if both will work like in C#.

**Comment by pa9ey** [comment]
"@pa9ey I think `String` is a type and `string` is a name of the object."

How can that be a typo?

**Comment by pa9ey** [comment]
So the idea currently is, we have no classes.
You can `create` an object and you can `copy` a pre-existing one.
But, interestingly, [this commit](https://github.com/yegor256/eo/commit/b9450bc26c3ac2c146a01505cec10ef4e6e4b14b) got rid of the `copy` keyword from the Hello, World example.

This reminds me of [a previous conversation we had](https://gitter.im/yegor256/elegantobjects?at=57c73a16928ae0e73469d893) about getting rid of the `new` keyword.

If we want to get rid of `new` then it's no good replacing it with `copy`.

So I'm still thinking about how to make this work with the Hello, World example...

**Comment by mdbs99** [comment]
@pa9ey have you seen this syntax [here](https://github.com/yegor256/eo/issues/6)?
What do you think about it?

**Comment by pa9ey** [comment]
@mdbs99 Yes, I have. I took a good look at it before I wrote some of my recent stuff.

Right now I'm not a huge fan of it, if I'm honest. It seems too cluttered and wordy. I want to be able to compose new objects (networks of objects) in a simple, readable, un-noisy style. (That's my feeling. Though I recognise I might be being naive.)

I'm not pretending that that's an easy or practical thing to do, or that I understand how you would do it. It's just something I'd like to aim for.

**Comment by pa9ey** [comment]
I'm imagining (again, perhaps naively) something like this:

```
var whatIWant = Thingamajig(
   Whatsit(
      Oojama("flip"),
      Thingama("bob")
   ),
   Doodah()
).Start("the magic");
```

Now if you imagine that, but with nice domain-y names rather than silliness, it's something like what I'm hoping for.

You can actually get this kind of thing in C++ if you create everything on the stack. But of course that's Class-based syntax...

**Comment by pa9ey** [comment]
@mdbs99 Sorry, I realise now I might be missing your point. My example just ignores all the "mess", which is hidden away in Class definitions somewhere. And we're obviously supposed to be doing away with those...

Maybe I'm just not a fan of the prototype idea yet. :grimacing:

**Comment by mdbs99** [comment]
@pa9ey nothing was defined yet. Just ideas.

**Comment by yegor256** [comment]
@pa9ey I like the explanation given by @SilasReinagel above. We have types, which are literally Java interfaces -- this is clear. And we have objects, which can be created or copied. To create an object we have to define its _body_. To copy an object we have to use another object with different constructor arguments. Maybe I have to submit a pull request with this explanation and we'll discuss?

**Comment by mdbs99** [comment]
@yegor256 sounds good to me. Submit the explanation.

**Comment by pa9ey** [comment]
@yegor256 I think I'm slowly catching up. :)

So I guess it's true then that `cli(printed(string))` is not valid. Correct?

That must be because `string` isn't an object in _exactly_ the same sense as the object that is constructed by calling `string("blah")` is an object. `string` must be some sort of "template" that produces objects of that type. But this sounds very like the definition of a class, which is maybe why I was getting confused.

Could you say that `string` is an object of type Foo, and sending the constructor "message" to `string` produces an object of type String (whose implementation has been defined in the `string` object)?

**Comment by yegor256** [comment]
@pa9ey not really. `string` is an object with, say, `"Hello, world!"` inside (or an empty string). You can use it directly or you can copy it. Make sense?

**Comment by pa9ey** [comment]
Oh boy, I'm confused. :grinning: 
So this **_would_** be a valid program?
```
import org.eolang.printed;
import org.eolang.string;
cli(
  printed(string)
)
```
That's what I suggested originally, but @SilasReinagel said it wouldn't be and I thought you had agreed with him so I was trying to come up with other possibilities. 

Anyway, I think [my very first comment](https://github.com/yegor256/eo/issues/11#issue-188935936) (with the edit) is now accurate.

**Comment by yegor256** [comment]
@pa9ey yes, it's a valid code, however in our current syntax it will look like:

```
cli:
  printed:
    string
```

And it will print an empty string to console.

This one will print something else:

```
cli:
  printed:
    string:
      "Hello, world!"
```

What was your question again? :)

**Comment by pa9ey** [comment]
@yegor256 I think that's answered it now. :)
But the original point, which may have got a bit lost :smile:, was just an attempt to understand the `Hello, world` example. The last piece of the puzzle is that the `cli` object is presumably just always there and doesn't need importing.
I'll maybe submit a pull request to update the syntax and maybe add a bit of explanation.

**Comment by mdbs99** [comment]
@pa9ey take a look [here](https://github.com/yegor256/eo/issues/20#issuecomment-261328134).

**Comment by DronMDF** [comment]
`string` is valid, and empty string.
`string("Hello world!")` should be not valid, but string already created. string is immutable.
`("Hello world") from string` anonymous object? :)

@yegor256 you can explain this example? How define cli, printed, string? This is another syntax. :)
```
cli:
  printed:
    string:
      "Hello, world!"
```

**Comment by pa9ey** [comment]
@DronMDF
-  `string` is the name of an object, presumably of type `String`, that has been created in `org.eolang`.
- The fact that we're passing in an argument means that we're actually constructing a new object by copying the existing one.
- In a similar way `printed` is already exists as an object.
- I think `cli` just automatically exists and doesn't need importing. (It also automatically executes itself.)

**Comment by yegor256** [comment]
@pa9ey @DronMDF @mdbs99 check README and this 		2c95e8a

**Comment by pa9ey** [comment]
@yegor256 Nice! Really seeing the shape of it now. It might take me a while to get comfortable with all of it and I'm very intrigued to see if, practically, some of those ideas will work, but it's certainly something to get your teeth into.

And I've got a feeling you'll have this all up and running before I've fully worked out how to use GitHub... :sweat_smile:
