### ISSUE TITLE
More laconic syntax?

### ISSUE THREAD

**Issue by gukoff** [yegor256/eo#12]
Good code is both short and well readable. Good code doesn't repeat itself twice.

Essentially, when the code is consistently indented, the semicolons, curly braces, Ruby's `end` or any other block indentation techniques are tautological. Python is a good example of a laconic(and potentially object oriented!) language, where the whitespace indentation is the block indentation at the same time.

Compare
```
type Book {
  String asText();
}

create abc("The Alphabet") as Book {
  String isbn;
  String title;
  Book(ISBN i, String t):
    isbn(i),
    title(t);
  String asText() {
    copy sprintf(
      "ISBN is %s, title is '%s'",
      this.isbn,
      this.title
    )
  }
}
```
and something like this:
```
type Book:
    String asText()

abc("The Alphabet") as Book:
    String isbn
    String title
    
    constructor(ISBN i, String t):
        @(isbn=i, title=t)

    String asText():
        copy sprintf(
            "ISBN is %s, title is '%s'",
            isbn, title
        )
```

The constructor syntax is free to negotiate. There are a lot of ways it could be written the other way. 
In my example the `@` operator would require to initialize **all** fields of the object.

**Comment by pa9ey** [comment]
I'm tempted to agree.

I've always been most comfortable with curly-braces and semi-colons, but seeing F# started to change my mind. Or at least make me question it.

I like the way it pretty much forces you to write short, well indented, lines of code. (I try to do that anyway, but maybe having the compiler enforce it is a good idea.)

**Comment by mdbs99** [comment]
I think we can throw away curly-braces and semicolons, but IMO a rigid indentation of code isn't good.

**Comment by pa9ey** [comment]
I'm not sure that's possible. If you have no curly-braces or semicolons I think you have to have indentation or you will have parsing issues.

**Comment by mdbs99** [comment]
Of maybe we can use just an `end` keyword.
I will rewrite the first example in this thread:

```
type Book 
  String asText()
end

create abc("The Alphabet") as Book
  String isbn
  String title
  Book(ISBN i, String t)
    isbn(i),
    title(t);
  end
  String asText()
    copy sprintf(
      "ISBN is %s, title is '%s'",
      this.isbn,
      this.title
    )
 end
end
```

**Comment by gukoff** [comment]
> I'm not sure that's possible. If you have no curly-braces or semicolons I think you have to have indentation or you will have parsing issues.

In fact, the parsing wouldn't be an issue. One can easily preprocess a source file and add the semicolons or curly braces, and then run some (if the grammar will be deterministic and context-free) LR(1) parser to build the AST. 


> Of maybe we can use just an end keyword.
I will rewrite the first example in this thread:

Looks tautological to me... Perhaps even worse than a curly brace, 3 symbols vs 1.

**Comment by mdbs99** [comment]
> Looks verbose and tautological to me... Perhaps even worse than a curly brace, 3 symbols vs 1.

Sometimes verbosity is good, if we know use it in the right way.

**Comment by pa9ey** [comment]
@gukoff Do you know of any langauges with neither braces/semicolons nor indenting?

**Comment by gukoff** [comment]
>>Looks verbose and tautological to me... Perhaps even worse than a curly brace, 3 symbols vs 1.

>Sometimes verbosity is good, if we know use it in the right way.

Maybe, but I don't think this is the right way. What is the reason to write these `end`s?

> @gukoff Do you know of any langauges with neither braces/semicolons nor indenting?

Ruby. Also, Visual Basic and Pascal, which has semicolons. Bash and Fortran as well.
Ruby is the best of the list, still verbose though.

**Comment by pa9ey** [comment]
@gukoff Oh okay. I'm not sure we're talking about the same thing. `begin` and `end` are the same as `{` and `}` as far as I'm concerned, except worse perhaps.

**Comment by mdbs99** [comment]
> Maybe, but I don't think this is the right way. What is the reason to write these ends?

@gukoff the reason is make a block of code, like in Pascal (begin/end), but I think the `begin` keyword isn't necessary.

**Comment by gukoff** [comment]
> @gukoff Oh okay. I'm not sure we're talking about the same thing. begin and end are the same as { and } as far as I'm concerned, except worse perhaps.

Sure. No, I can't recall any other block indentation technique, but it would be great to consider all the alternatives.

>> Maybe, but I don't think this is the right way. What is the reason to write these `end`s?

>@gukoff the reason is make a block of code, like in Pascal (begin/end), but I think the begin keyword isn't necessary.

But the `end` keyword is exactly alike. Unnecessary, if the code is indented with whitespaces.
I think of the whitespace indentation as being a de-facto necessary thing. And languages like Python or Haskell show that it might be sufficient for block indentation and affect the readability in a good way.

It's worthwhile to mention, that I am assuming we're inevitably going to use blocks of code to define types, objects and methods.

**Comment by mdbs99** [comment]
Well, at this moment I don't like the idea of make blocks just using whitespaces, TAB or both.

**Comment by pchmielowski** [comment]
I personally like curly braces. I like the fact, I can just write a few lines of code without thinking of indention, and then put `}` and hit `[Ctrl]+[Alt]+[L]` (auto-indention in AndroidStudio) and IDE is doing work for me.

**Comment by gukoff** [comment]
> Well, at this moment I don't like the idea of make blocks just using whitespaces, TAB or both.

+

> I personally like curly braces. I like the fact, I can just write a few lines of code without thinking of indention, and then put } and hit [Ctrl]+[Alt]+[L] (auto-indention in AndroidStudio) and IDE is doing work for me.

Well, these aren't really the arguments? Looks like a matter of habit, a habit not to notice a syntax noise. Look at what @pa9ey said:
>I'm tempted to agree.
>I've always been most comfortable with curly-braces and semi-colons, but seeing F# started to change my mind. Or at least make me question it.

**Comment by mdbs99** [comment]
@gukoff IMO, code is not like a config file that we could use whitespaces or TAB. I like to indent my code. I do not use any tools for that because my own style is better for me.

**Comment by alex-semenyuk** [comment]
I think indent approach to teach programmers be more orderly with code, because in other cases programmers can communicate the scoping of the code in two distinct manners for every single line of code, let's paraphrasing - should be strict rules in this case. If think deeply curl braces and begin\end it is redundant code. So if code is well intend -  it's well readable and maintainable IMO.

**Comment by mdbs99** [comment]
@alex-semenyuk not `begin/end`, just `end` like Ruby.

**Comment by yegor256** [comment]
@gukoff I like this idea, a lot. Can you please submit a pull request?

**Comment by kapilbhudhia** [comment]
"I do not use any tools for that because my own style is better for me."
@mdbs99  But don't you you end up reading other people code and vice versa?

**Comment by mdbs99** [comment]
@kapilbhudhia yes, but my code, in my company, with my team, we would to use our style.

**Comment by gukoff** [comment]
Sorry for the mess above, putting a link to this issue into a commit message was a mistake.
We can continue our conversation in the pull request.

**Comment by yegor256** [comment]
@gukoff thanks, merged! I think you can close the ticket.

**Comment by gukoff** [comment]
👍
