### ISSUE TITLE
ArgumentTest.java:41-46: Object instantiation as constructor...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/eo#129]
The puzzle `104-4512cd36` in [`eo-compiler/src/test/java/org/eolang/compiler/syntax/ArgumentTest.java`](https://github.com/yegor256/eo/blob/master/eo-compiler/src/test/java/org/eolang/compiler/syntax/ArgumentTest.java) (lines 41-46) has to be resolved: Object instantiation as constructor argument. We should be able to pass new object as constructor argument. This is not implemented now because it's not so simple to save constructing object and argument object to different java classes (different files). Maybe we can save argument object as nested java class.

The puzzle was created by rultor on 20-Mar-17. 

Estimate: 60 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `104-4512cd36` has disappeared from the source code, that's why I closed this issue.
