### ISSUE TITLE
MethodImpl.java:33-36: Object instantiation in method body...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/eo#131]
The puzzle `105-90b91742` in [`eo-compiler/src/main/java/org/eolang/compiler/syntax/MethodImpl.java`](https://github.com/yegor256/eo/blob/master/eo-compiler/src/main/java/org/eolang/compiler/syntax/MethodImpl.java) (lines 33-36) has to be resolved: Object instantiation in method body is not implemented We should be able to create new object inside methods. It may be implemented as java nested class in same object-class (just to my mind).

The puzzle was created by rultor on 25-Apr-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `105-90b91742` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/eo#131` is not assigned, can't get performer
