### ISSUE TITLE
Removing the new operator

### ISSUE THREAD

**Issue by ixmanuel** [yegor256/eo#133]
I think "new" operator should be removed from EO, because it is a legacy concept. It comes from languages where we need to deal with their implementation. "new" is about low level operations. "new" doesn't get along with the different levels of abstraction:

new PersonID means that the machine have to allocate memory, but if an object brings the personID from a data store, then the object is reconstituing the entity but it is not creating a new one (not in the terms of the domain)

If we think that objects are on a stage, they appear as players that interact with each other, but do not need to be born in each scene. They only need to appear on the scenes that are required.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by ixmanuel** [comment]
I'm sorry, you're right. I'm closing this, but I think the same concern applies to the keyword ctor (). I will talk about this there.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/eo#133` was not in scope

**Comment by pa9ey** [comment]
That's very kind, but I can't really accept that I was right. I asked a question. :)

**Comment by ixmanuel** [comment]
Yes, there is no new in the proposal, but the underlying concept is still alive in the constructor keyword, so I posted this concern in: https://github.com/yegor256/eo/issues/49
