### ISSUE TITLE
ProgramTest.java:85-87: For some reason this test doesn't...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/eo#139]
The puzzle `138-7ad7d775` in [`eo-compiler/src/test/java/org/eolang/compiler/ProgramTest.java`](https://github.com/yegor256/eo/blob/master/eo-compiler/src/test/java/org/eolang/compiler/ProgramTest.java) (lines 85-87) has to be resolved: "For some reason this test doesn't work. Let's investigate and fix. It stopped to work after I introduced strict error checking in ANTLR."

The puzzle was created by yegor256 on 10-Jul-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/eo#139` was not in scope
