### ISSUE TITLE
Let's use cactoos

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/eo#141]
Let's use cactoos'es primitives.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@alex-semenyuk good idea, pls go ahead

**Comment by alex-semenyuk** [comment]
#142

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/eo#141` was not in scope
