### ISSUE TITLE
ProgramTest.java:52-55: Two tests are disabled here because...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/eo#145]
The puzzle `144-b64024e6` (from #144) in [`eo-compiler/src/test/java/org/eolang/compiler/ProgramTest.java`](https://github.com/yegor256/eo/blob/master/eo-compiler/src/test/java/org/eolang/compiler/ProgramTest.java) (lines 52-55) has to be resolved: "Two tests are disabled here because there is something wrong with our ANTLR syntax. We should be able to parse the files provided, but they fail. Let's find out and fix."

The puzzle was created by Yegor Bugayenko on 06-Aug-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/yegor256/eo/issues/145#issuecomment-320521359))

@yegor256 Job `gh:yegor256/eo#145` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @g4s8 is not a member of this project yet, but can request to join. @g4s8 check your [Zerocracy profile](http://www.0crat.com/u/g4s8) and follow the instructions.

**Comment by 0crat** [comment]
+15 points just awarded to @0pdd, total is [+135](http://www.0crat.com/u/0pdd).

**Comment by yegor256** [comment]
@g4s8 would be great if you can take a look. I'm stuck now, because of this weird problem with the syntax.

**Comment by g4s8** [comment]
@yegor256 sure, I'll see what can I do

**Comment by g4s8** [comment]
@yegor256 I fixed grammar rules, but broke java code generation. Now eo code can be parsed with strict ANTLR error handling. I suppose to complete this task within week.

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0pdd** [comment]
The puzzle `144-b64024e6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/eo#145` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @g4s8, total is [+1605](http://www.0crat.com/u/g4s8).
