### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by filfreire** [yegor256/eo#148]
Tasks:
* Follow Github guideline https://github.com/blog/1184-contributing-guidelines of having a separate contributing file
* Replace "How to contribute" section's content with a link to CONTRIBUTING.md

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/yegor256/eo/issues/148#issuecomment-335135477))

@yegor256 Job `gh:yegor256/eo#148` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @g4s8 is not a member of this project yet, but can request to join. @g4s8 check your [Zerocracy profile](http://www.0crat.com/u/g4s8) and follow the instructions.

**Comment by g4s8** [comment]
@filfreire added here: #150, can we close this?

**Comment by filfreire** [comment]
@g4s8 @yegor256 issue closed 👍

**Comment by 0crat** [comment]
Job `gh:yegor256/eo#148` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8, total is [+2475](http://www.0crat.com/u/g4s8).
