### ISSUE TITLE
Replacement for "if" operator

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/eo#15]
From the README:

```
These things we don't tolerate:
- operators (for, while, if, etc)
```

While it is not particularly hard to encapsulate conditional operations like the "if" operator, I do not know of a way to get around having it exist somewhere. 

In C#, I am able to create objects like this:
```
public class ConditionalAction
{
    private readonly Func<bool> condition;
    private readonly Action action;

    public ConditionalAction(Func<bool> condition, Action action)
    {
        this.condition = condition;
        this.action = action;
    }

    public void Invoke()
    {
        if (condition.Invoke())
            action.Invoke();
    }
}
```

This makes it so that calling code no longer requires the "if" operator, but it does require the instantiation of an object for every conditional action. It moves the problem elsewhere, but doesn't entirely solve it. 

That would transform this code:

```
if (!heater.IsRunning())
    heater.TurnOn();
```

Into this:

```
var turnOnIfNotRunning = new ConditionalAction(() => !heater.IsRunning(), () => heater.TurnOn());

turnOnIfNotRunning .Invoke();
```

The second one is slightly more object-oriented (it utilizes functional-style lambdas), but it seems more complex and more verbose.

What is a more elegant way to replace the "if" operator?

**Comment by SilasReinagel** [comment]
This wouldn't solve the problem of not being Object-Oriented, but a more concise syntax could be this:

`!heater.IsRunning() ? heater.TurnOn()`

**Comment by mdbs99** [comment]
I recommend see [this video](https://github.com/yegor256/eo/issues/5#issuecomment-260607367), when she talk about `If` in Smalltalk, doing the same in Ruby.

**Comment by yegor256** [comment]
@SilasReinagel I think that our code will look very close to Lisp, for example (Fibonacci):

```
int fibo(int n):
  if:
    lessThan: n, 2
    1,
    fibo: 
      minus: n, 1
```

Make sense?

**Comment by yegor256** [comment]
@SilasReinagel here `if`, `lessThan`, and `minus` are objects we copy.

**Comment by yegor256** [comment]
@SilasReinagel here is Lisp code to compare with:

```
(defn fibo n
  (if (< n 1)
    1
    (fibo (- n 1))))
```

**Comment by yegor256** [comment]
@SilasReinagel please, review README

**Comment by MadridianFox** [comment]
You're forgot that Lisp works with functions, which invoked immediately. With objects we should to instantiate an object and invoke his method.

**Comment by Tertioptus** [comment]
int fibo(int n):
  Predicate:
    lessThan: n, 2
    1,
    plus:
      n
      fibo: 
        minus: n, 1

**Comment by yegor256** [comment]
@SilasReinagel I think this ticket can be closed, we already agreed about "control flow" operator replacements in EO
