### ISSUE TITLE
http://www.eolang.org/ redirects endlessly

### ISSUE THREAD

**Issue by Serranya** [yegor256/eo#152]
When I try to open http://www.eolang.org/ I just get redirected endlessly.

![grafik](https://user-images.githubusercontent.com/1206309/49735937-f4589d00-fc88-11e8-8d6d-d75ab40be272.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@serranya[/z](https://www.0crat.com/u/serranya) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@Serranya fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/eo#152` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
