### ISSUE TITLE
enable integration tests in Maven plugin

### ISSUE THREAD

**Issue by yegor256** [yegor256/eo#168]
Let's do it

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.7`

**Comment by 0crat** [comment]
Job `gh:yegor256/eo#168` is not assigned, can't get performer
