### ISSUE TITLE
do we need brackets?

### ISSUE THREAD

**Issue by yegor256** [yegor256/eo#17]
I don't think we need brackets. Look at this code:

```
String asText():
      copy sprintf(
          "ISBN is %s, title is '%s'",
          this.isbn,
          this.title
      )
```

And this one:

```
String asText():
      copy sprintf:
          "ISBN is %s, title is '%s'",
          this.isbn,
          this.title
```

Better, right?

**Comment by yegor256** [comment]
As suggested in #15, here is our syntax for Fibonacci function:

```
int fibo(int n):
  if:
    lessThan: n, 2
    1,
    plus:
      n
      fibo: 
        minus: n, 1
```

**Comment by yegor256** [comment]
Pay attention, there are **no** statements. It looks like functional programming, but it's object-oriented one. Thus, we will make all fans of FP happy, and will stay in the OOP domain :)

**Comment by alex-semenyuk** [comment]
Yes, it looks clear. I think need to keep one direction, I mean if we wouldn't like begin, end, etc as redundant and stay with major thing as indents that lets remove brackets as well

**Comment by yegor256** [comment]
Pull request is in: #19
