### ISSUE TITLE
add more tests and integration tests

### ISSUE THREAD

**Issue by yegor256** [yegor256/eo#173]
let's add more unit and integration tests and make sure they work with the current version of EO-to-Java compiler

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.8`

**Comment by 0crat** [comment]
Job `gh:yegor256/eo#173` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.10`
