### ISSUE TITLE
Git commit messages standard

### ISSUE THREAD

**Issue by vgaidarji** [yegor256/eo#2]
Hello @yegor256.

I'm curious how far this language can evolve 👍 

By the way, what's your opinion on git commit messages format?
I see that you don't follow any rules and simply name commits as short as possible:
<img width="319" alt="screen shot 2016-11-11 at 4 39 01 pm" src="https://cloud.githubusercontent.com/assets/3036347/20218457/c6ec1878-a835-11e6-8e56-962e174db538.png">

There's a well known standard described in [Chris's Beams blog](http://chris.beams.io/posts/git-commit/) and I bet you read it. 
Is there a real reason to not to follow this best practices?

**Comment by yegor256** [comment]
@vgaidarji I'm using these short messages just for now, until the skeleton is ready. Should stop doing them today and will work through pull requests, like everybody else. Thanks for pointing out.

**Comment by yegor256** [comment]
@vgaidarji did I answer the question? if so, please close the ticket
