### ISSUE TITLE
I don't think we need "copy" keyword

### ISSUE THREAD

**Issue by yegor256** [yegor256/eo#20]
Looks like `copy` keyword is redundant. I'm suggesting this:

```
type Point:
  Point moveTo(int x, int y)
object cursor(0, 0) as Point:
  Number @x
  Number @y
  Point moveTo(int x, int y):
    cursor: # here we COPY an object
      plus: @x, x
      plus: @y, y
```

No need to use `copy` at all. Just `type` and `object` are the keywords we need. What do you think?

**Comment by DronMDF** [comment]
I do not understand how to create a number of different objects of the same type.

type Person:
    ....

object yegor256 as Person:
    ...

object dron as Person:
    ...

dron is not a copy of yegor256...

**Comment by yegor256** [comment]
@DronMDF you create one object first, and call it, say `somebody`. Then, you copy `yegor256` and `dron` from it:

```
type Person:
    ....
object somebody("noname") as Person:
yegor256("Yegor Bugayenko")
dron("Andrey Valyaev")
```

See?

**Comment by DronMDF** [comment]
Where is specified, that yegor256 it is Person or copy of somebody?

`yegor256("Yegor Bugayenko")`

**Comment by yegor256** [comment]
@DronMDF I didn't understand the question(s). Can you re-write the first one again please?

**Comment by DronMDF** [comment]
Sorry. :(

`yegor256("Yegor Bugayenko")`

Is where object type? How can i find it?

**Comment by mdbs99** [comment]
@yegor256 and @DronMDF 
The first syntax is wrong.
What about this?
```
type Person:
    ....
object somebody("noname") as Person:
    ....
object yegor256("Yegor Bugayenko") from somebody
object dron("Andrey Valyaev") from somebody
```

**Comment by mdbs99** [comment]
About `string` I suggest this:
`object string("Hello, world!")`

**Comment by DronMDF** [comment]
@mdbs99:
Where prototype?

`object string("Hello, world!") from basicstring`

**Comment by mdbs99** [comment]
@DronMDF you're right.
So, another syntaxe, a little bit different:

```
type String:  // a built-in type
...
object string as String
object hello("Hello, world!") from string
```
The "prototype" will be `string`, ie, an object that implements `String`.

**Comment by DronMDF** [comment]
Hello world example should be look differ.

**Comment by mdbs99** [comment]
@DronMDF I think so.

@yegor256 what do you think?

**Comment by pa9ey** [comment]
@mdbs99 Yeah, I'm not exactly sure I follow what's going on with all of this. I don't understand Yegor's comment/example above. I would've expected something like this:
```
type Person:
    ....
create person("noname") as Person:
    ....
yegor256 = person("Yegor Bugayenko")
dron = person("Andrey Valyaev")
```
Except that there doesn't appear to need for "variables" in this scheme, so he can't have meant exactly that.
(I'm catching up on lots of reading of issues and comments at the moment so that's the best I can do.) :)

**Comment by yegor256** [comment]
hey guys, we won't have variables, keep this in mind!

**Comment by yegor256** [comment]
@pa9ey please, review the latest version of README, I've made many changes a few minutes ago

**Comment by DronMDF** [comment]
```
type Person:
    ....
person("anonymous") as Person:
    ctor(String name)
```

And later, names is not need. No variables! Ok.
```
person: "Yegor"
person: "Andrey"
```

Or
```
person: string: "Yegor"
person: string: "Andrey"
```

I'ts right syntax?
`string` is need? Or is this implicit?

**Comment by yegor256** [comment]
@DronMDF that's a good question about String, I will explain it now in README

**Comment by yegor256** [comment]
No `copy` keyword any more, I'm closing this ticket
