### ISSUE TITLE
Contructors and Destructors

### ISSUE THREAD

**Issue by mdbs99** [yegor256/eo#29]
That issue is about: 
https://github.com/yegor256/eo#constructors-and-destructors

> The primary constructor must be the last one. The destructor, if it is present, goes right after the primary constructor.

Why the last one? The primary has to be the first, on top.

Another thing. See this code (copied from README):

```
object zero() as Money, Int:
  Int @amount
  String @currency
  zero(): # secondary constructor
    zero: 0
  zero(Int a): # secondary constructor
    zero: a, "USD"
  zero(Int amount, String currency) # primary constructor
  ~zero(): # destructor
    printed: "I'm dying..."
```
I think constructor shouldn't use the Object name. Maybe `ctor` or `constructor`.
The same for destructor, maybe `dtor` or `destructor`.
My vote is to use `constructor` and `destructor`.

And, please, throw away this `~zero()`. I think nobody want to remember C++, right?

**Comment by fabriciofx** [comment]
@mdbs99 I agree. ```construtctor``` and ```destructor``` are better names.

**Comment by yegor256** [comment]
@mdbs99 my initial idea was to use `ctor` and `dtor`. Let's collect some opinions and I will make changes.

**Comment by DronMDF** [comment]
ctor/dtor is preferred to me. Use object name as ctor/dtor is not obviously. Especially given the specialization.

Question:
```
object shape as Shape: ...
object rectangle extend shape:
```
rectangle can public shape ctor? Or base class ctor is private?

Other example:

```
object error as Error:
    ctor(String: what):...
object logic_error extend error:
    // Need ctor?
```

Hm... This extend does not make sense with some type of object. Maybe parent ctor need only for private use.

**Comment by mdbs99** [comment]
@DronMDF there is no inheritance for Objects, just specialization for Types.

**Comment by pa9ey** [comment]
> Why the last one? The primary has to be the first, on top.
@mdbs99 Yegor wrote about this [here](http://www.yegor256.com/2015/05/28/one-primary-constructor.html).

**Comment by mdbs99** [comment]
@pa9ey yes, I know, and agree with him — I have done this ~2 years before this article.
I guess you didn't understand me right:

>Why the last one? The primary has to be the first, on top.

I meant: If the compiler will check the precedence, the primary ctor should be the first wrote in the code.

**Comment by gukoff** [comment]
Do we need an explicit primary constructor? It seems to be the same all the time - something which accepts all the attributes and sets them as-is.

**Comment by pa9ey** [comment]
@mdbs99 I understood you. You were asking why the last one. Yegor addresses that very question in the article. I wasn't suggesting you should agree with it, nor that I do (or don't) - I was simply pointing out that he addresses your question, the one that I quoted.

**Comment by pa9ey** [comment]
@gukoff Good point.

**Comment by mdbs99** [comment]
@gukoff I don't. What I want is that compiler not check if the "primary ctor" was wrote at the end. Just that.

@pa9ey I'm sorry. I read the article again:
*...a primary constructor, and it will always be easy to find because it stays below all secondary constructors*.
Now I understood what you meant. But I disagree of Yegor in that case.

**Comment by pa9ey** [comment]
@mdbs99 Sure. And I guess it would be just as easy to find if it was always first. Just a preference I guess.

**Comment by mdbs99** [comment]
So @yegor256, `ctor` and `dtor` won?

**Comment by gukoff** [comment]
>>Do we need an explicit primary constructor? It seems to be the same all the time - something which accepts all the attributes and sets them as-is.

> @gukoff I don't. What I want is that compiler not check if the "primary ctor" was wrote at the end. Just that.

No, I've addressed the concept, not your particular issue :)

Speaking of languages like Java, the requirement for a primary constructor to be written at the end looks logical. It reminds me of the common rule of putting private below public. The secondary constructors must be public; otherwise, they are useless. A primary constructor is sometimes public just to be used in unit testing and serves as a basis for the secondary ones.

**Comment by mdbs99** [comment]
> ...a primary constructor to be written at the end looks logical.

@gukoff I don't see any logica here sorry. Anyway...
if I can put the constructors and methods in the sequence I want, without the compiler interfering, it will just be a matter of style. That just all I need.

**Comment by krzysiekpiasecki** [comment]
>> Constructors must be listed after attributes. The primary constructor must be the last one. The destructor, if it is present, goes right after the primary constructor.

We're talking about inline or temporal dependencies as a bad pratice, but we should write ```ctors dtors attrs``` in expected order? What I have missed?

**Comment by mdbs99** [comment]
@yegor256 `ctor` and `dtor` won?
Can I close this issue?

**Comment by evgeniynickolaev** [comment]
+1 for ctor/dtor

**Comment by MonsieurLuge** [comment]
+1 for constructor & destructor (readability in mind)

**Comment by gukoff** [comment]
Guys, it isn't going to be written in stone :) For the time being, both `ctor` and `constructor` are fine.

**Comment by mdbs99** [comment]
@gukoff I agree with you.
So as @yegor256 didn't tell anything all these days and we've already voted, I'll finish this issue and, after, change the README if nobody does.

**Comment by yegor256** [comment]
@mdbs99 please submit a pull request for `ctor` and `dtor`. thanks!
