### ISSUE TITLE
New language name proposal

### ISSUE THREAD

**Issue by englishman** [yegor256/eo#3]
Just idea to add 'L' to the end of the new language name to make it: *Elegant Objects Language*. This makes the language acronym to *EOL*.

This acronym, from the one side, is [well known for all programmers](https://en.wikipedia.org/wiki/Newline) already and, from the other side in Russian language [Эол](https://ru.wikipedia.org/wiki/%D0%AD%D0%BE%D0%BB) is a name of a demigod.

WDYT?

**Comment by yegor256** [comment]
too late :) but I like the idea. we can pronounce it "eol" and write as "eo".

**Comment by englishman** [comment]
@yegor256 why too late?! it looks like you already have some legacy heritage :smile:

**Comment by mdbs99** [comment]
@englishman I think is too late because @yegor256 already registered the domain.

**Comment by yegor256** [comment]
@englishman yeah, the domain is out there and we're in the news already: https://twitter.com/yegor256/status/797079615089111042

**Comment by krzysiekpiasecki** [comment]
I think "Elegant object" as language name is not elegant because it's strong releated to the market product (book and author"). Also the idea is very general and weak.


The new language is a subset of used OOP techniques. So it's an object oriented esperanto ;)

**Comment by yegor256** [comment]
@krzysiekpiasecki yes, Esperanto is the idea :)

**Comment by yegor256** [comment]
@englishman I guess it's time to close this ticket :)

**Comment by englishman** [comment]
@yegor256 should I close?

**Comment by yegor256** [comment]
@englishman yes, please. In general, the author of the ticket must close it, check this out: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by pa9ey** [comment]
@yegor256 Interesting article! Makes me think about my open tickets. At the moment though, the roles are not so clear. I've reported the "problems" (opened the tickets) but I'm also (kinda) the solver and am just collecting others' thoughts. There's not necessarily that two-way conversation. I'll have a good think about my tickets though...

(Sorry, this comment, on this ticket, is committing the sin of "noise". ;)
