### ISSUE TITLE
Ambiguous copy syntax

### ISSUE THREAD

**Issue by DronMDF** [yegor256/eo#30]
`if` is a object with three args. Full expressions look like this: `if: condition, then, else`

Any arg contain object create expression (in most cases)
For example `equals: p, 0`

I can write this code:
`if: equals: p, 0, 1, mul: x, power: x, minus: p, 1`

Where is **then** arg?
Compiler can parse this.
Question about readability.

In readme - missing semicolon after equal expression and 1

```
Int power(? x, Int p):
  if:
    equals: p, 0
    1
    mul:
      x,
      power: x, minus: p, 1
```

**Comment by yegor256** [comment]
@DronMDF typo fixed in 9da7364 Thanks!

**Comment by yegor256** [comment]
@DronMDF I think we should prohibit multi-line syntax, like the one you proposed above

**Comment by DronMDF** [comment]
I wait for working language prototype. :)
