### ISSUE TITLE
Convert to multi languages

### ISSUE THREAD

**Issue by amorenew** [yegor256/eo#38]
I wonder if it could be designed in way that allow it to be translated into several languages easily 
like java , c++ ,python and swift
also if it support MVVP or MVC in it core design.

**Comment by yegor256** [comment]
@amorenew yes, we're planning to make it compilable to all possible languages, including C/C++. I will add it to README now.

**Comment by yegor256** [comment]
@amorenew fixed 291872a Please, close the ticket if I answered your question

**Comment by amorenew** [comment]
@yegor256 thanks
