### ISSUE TITLE
The If object is not a good object

### ISSUE THREAD

**Issue by kanghj** [yegor256/eo#46]
According to http://www.yegor256.com/2014/11/20/seven-virtues-of-good-object.html, there are seven virtues for a good object. These include: 

* He Exists in Real Life
* He Works by Contracts

As far as I can tell, the `If` object does not satisfy these 2 requirements. I don't see any "If"s in real life. What real life object does an `If` object represent? And what `type`/`interface` would an `If` object belong to?

**Comment by Tertioptus** [comment]
I concur.  The abstraction of the proposed object could be "Predicate".  So this object is predicated on the terms provided (parameters).  And I would not shorten the word to save keystrokes.

Something to this effect:
type Item
price $4
---purchase $3(amount)
------Predicate
---------amount>=price success
---------amount<price error

**Comment by stain** [comment]
`If` is a "Choice" - and we have plenty of choices in real life. "I had to make a choice; am I hungry enough to buy a burger, or should I just have a chocolate?"

The contract of `If` is a kind of contextual generic, #1, as it has a return type depending on where it is used (both if/else branches must return a compatible type).

However I think you would need code/functions as first class objects for the parameter signatures of `If`.

**Comment by yegor256** [comment]
@kanghj I agree with @Tertioptus and @stain here. `If` indeed is a predicate and it does exist in real life. It represents a condition and two objects.
