### ISSUE TITLE
Perhaps extensible syntax? 

### ISSUE THREAD

**Issue by adrian-herscu** [yegor256/eo#51]
All languages today provide a fixed set of tokens , keywords, and constructs. What about letting users define their own "little languages" and have them supported by the tools?

**Comment by yegor256** [comment]
@adrian-herscu I'm personally strongly against that kind of DSL's. I believe that they only make code less readable. I'm using Ruby a lot and I really hate their DSL's. Very often I simply can't understand what the code does and have no idea where to look for documentation. So, I'm in favor of a very strict and specific syntax. No sugars, no DSLs, etc. See aa56f21

**Comment by ArneBachmann** [comment]
Agree. Languages with too much "magic" give me the creeps (e.g. Elixir, Ruby frameworks)

**Comment by flammar** [comment]
As I understand, every such custom DSL uses the idea of using compile-time analysis, mainly in IDE, to verify a statement in this DSL. Also, a question about DSL is not always a question about syntax extensibility, e.g. Scala-based DSLs.

**Comment by lebel-louisjacob** [comment]
@yegor256 I believe there should be space for DSLs in a general programming language. Otherwise, boilerplate code will probably be necessary for some particular tasks.

In an attempt to support my point of view, I want to point out that the README already contains some code that could be considered as beloning to a DSL. Namely, the `printf` function takes a string in which `%` is considered special character. If the argument to `printf` is not a DSL, I don't know what is :)

**Comment by kerelape** [comment]
> @yegor256 I believe there should be space for DSLs in a general programming language. Otherwise, boilerplate code will probably be necessary for some particular tasks.
> 
> In an attempt to support my point of view, I want to point out that the README already contains some code that could be considered as beloning to a DSL. Namely, the `printf` function takes a string in which `%` is considered special character. If the argument to `printf` is not a DSL, I don't know what is :)

`printf`'s `%` is not a language feature. You can always make your own parser for that using EO and no DSL in context of the language would appear

**Comment by ljleb** [comment]
> `printf`'s `%` is not a language feature. You can always make your own parser for that using EO and no DSL in context of the language would appear

You're reviving a very old thread!

In any case, I believe what I meant is that `printf`'s argument has its own domain specific syntax. Even though you put quotes around the argument, it still has to follow a domain specific syntax and isn't free form. AFAIK, the definition of a DSL is that it has to have a grammar, no matter whether the parsing occurs at runtime or compile time.
