### ISSUE TITLE
Anonymous objects

### ISSUE THREAD

**Issue by g4s8** [yegor256/eo#54]
I think object name `x` is redundant here:
_(readme example)_
```
Ticket ticket(Person passenger):
  object x(passenger) as Ticket:
    Person @p
    ctor(Passenger p)
    String name():
      concat:
        "506-",
        @p.name()
    Money price():
      if:
        @p.vip(),
        money("$50"),
        object m() as Money
          Int value():
            25
```
It may be clearer with anonymous object:
```
Ticket ticket(Person passenger):
  object (passenger) as Ticket:
    Person @p
    ctor(Passenger p)
      ...
```

**Comment by Lebedevsd** [comment]
@g4s8 if I want to create two different objects as Ticket, and both of them have Person as a ctor param. Then I will end up with the problem that the same notation could create 2 objects, and I do not know which will be created.

**Comment by g4s8** [comment]
> the same notation could create 2 objects, and I do not know which will be created.
@Lebedevsd, you can still use object name, if you want to create second object. I think anonimous objects should be similar to java anoanymous classes instances. In such way you won't be able to create one anonymous object twice.

**Comment by Lebedevsd** [comment]
@g4s8 how will you resolve this:
```
Ticket ticket(Person passenger):
  object x(passenger) as Ticket:
  ......

Ticket ticket(Person passenger):
  object y(passenger) as Ticket:
  ......

ticket(passenger: "Someone")
```
which object will be created x or y?

**Comment by g4s8** [comment]
@Lebedevsd , `Ticket ticket(Person passenger):` is a method. It's not allowed to define two methods with same signature in one scope.

**Comment by Lebedevsd** [comment]
@g4s8 Then it looks like static method, which is not the thing we wanna see in EO

**Comment by g4s8** [comment]
@Lebedevsd , it's an example from [Readme](https://github.com/yegor256/eo/blob/master/README.md) and it's out of any context, this method is just a method (not static). Furthermore it doesn't belong to this issue: "Anonymous objects".

**Comment by yegor256** [comment]
@g4s8 I like the idea. Do you want to submit a pull request with this?

**Comment by g4s8** [comment]
@yegor256, yes, I'll do it.
