### ISSUE TITLE
Fake objects

### ISSUE THREAD

**Issue by Lebedevsd** [yegor256/eo#55]
@yegor256 do you want to bring the same concept of [fake objects](http://www.yegor256.com/2014/09/23/built-in-fake-objects.html) as it was in your blog with java? 

```
type Book:
  String asText()
  object fake as Book:
    String @title
    ctor(title)
    String asText():
      title  
```

and later on use it like `Book.fake("Elegant Objects")`

in that scenario code from the read.me looks a bit confusing:

```
Ticket ticket(Person passenger):
  object x(passenger) as Ticket:
    Person @p
    ctor(Passenger p)
    String name():
      concat:
        "506-",
        @p.name()
    Money price():
      if:
        @p.vip(),
        money("$50"),
        object m() as Money
          Int value():
            25
```

Seems that you want to introduce static method to create Tickets, or the `x(passenger)`  will be visible outside?

**Comment by yegor256** [comment]
@Lebedevsd I'm totally in favor of that "fake objects", but your question is not really about them, if I understand it right. You're suggesting "inner objects", which are created inside types. Right?

**Comment by Lebedevsd** [comment]
@yegor256 yes and no, the first block of the code with the Book example is clear I think, but the second, which is taken from the readme.md is quite confusing. 
As far as I understand in this approach we could use `ticket(passenger)` from any place in the code, and it will create the instance of `object x`. So this is like fabric method, am I right?
In second block we use type as object, but not object as type.
