### ISSUE TITLE
License for specification and examples?

### ISSUE THREAD

**Issue by stain** [yegor256/eo#64]
What open source license should we use for this specification and its examples? It's beneficial for implementations to be able to use and modify the examples "as is", and similar for grammar rules.

**Comment by stain** [comment]
I just noticed that #58 branch [declares MIT license](https://github.com/yegor256/eo/blob/58/LICENSE.txt) -- let's just use that?

> Copyright (c) 2016 eolang.org

This is not valid as I don't think eolang.org is a legal entity (company, organization, etc).  "eolang.org contributors" perhaps is slightly better?

**Comment by yegor256** [comment]
@stain it's MIT now. I don't think we can put `eolang.org contributors` there, since it won't mean anything specific. If someone has copyright issues and wants to contact "the author", who will he contact? "contributors"? There are just too many of them :)

**Comment by yegor256** [comment]
@stain I closed this one, since it's "solved"

**Comment by stain** [comment]
Hmm.. but it's not really closed as there is not a LICENSE file and the license is not mentioned in the README. I'll do a PR.
