### ISSUE TITLE
Do we really need create new language?

### ISSUE THREAD

**Issue by moriline** [yegor256/eo#69]
I think that no any reison for creating new language with the different syntax. Let me explain my point.
These are some facts:
- All problems in IT development described by @yegor256 are exists. We all are agree with most of them.
- If we are set analogy with knife(Java language) and our skills(java libraries, frameworks, paradigms, patterns, etc...) for use it. And when we are using this knife with our skills our hands fills by blood. That is bad and sadly.
We are have 2 choices: change language or change our skills.
1) If we are want change language - we can do it. You can use Ceylon, Ruby, JRuby or other (Python, Scala, Groovy, etc...) On any taste. Also we can create new language and after some months or years one of us will be looked at it and will say: "Well... we are created a Ruby!". It is like a story about 15 standarts and we are try create another one... 
2) Or we are can change our skills. We can show to all developers our point of view for OOP, objects and how should to use it . And prove it by practice and show them that it works well. Practice the criterion of truth, isn't it? We can show right way for use Java and "true code".

It is a short version of my reasons, so, if you have any questions, please, ask me.

**Comment by yegor256** [comment]
@moriline Java (and other languages) don't allow us to do things we need in "true OOP". If we stop using all that Java "bad things" listed in README, we won't be able to create any decent Java application. So, it's technically not possible to make Java really object-oriented.

**Comment by moriline** [comment]
@yegor256 I disagree with this opinion. "it's technically not possible to make Java really object-oriented" - if think like that, then we are developed our applications by java ver 1.2 without last features. Or java developers in Sun implements these features taken from skies? Maybe other developers are requires these features?

**Comment by yegor256** [comment]
@moriline unfortunately, vast majority of Java developers are procedural programmers, and they like it. We can't change that situation but asking Oracle to, say, remove static methods and annotations from Java. They simply won't listen.

**Comment by Tertioptus** [comment]
yes

**Comment by OneWingedShark** [comment]
@moriline  
A lot of new languages are held back by being "let's try to fix C" (or some other language) -- while this project has a bit of that WRT Java, I do find it refreshing that it's not a "let's copy Java's syntax and and try to fix things there!"-style project.

Also, there's been generally good feedback from the issues I've raised ( #40 , #41 , #42 , #44 , #45 ) where I'm trying to point out how design in the semantic-space impacts the language itself -- which can be a little difficult because sometimes it's hard to understand how features interact, or if you do understand them describing the problem to other people.

**Comment by yegor256** [comment]
@moriline I think I answered the main question here: https://github.com/yegor256/eo/commit/3eff81d032d925fb8527d778081963475e62eeb6

**Comment by yegor256** [comment]
@moriline and thanks for raising this concern, it's valid indeed.
