### ISSUE TITLE
Kotlin style field initialization

### ISSUE THREAD

**Issue by pchmielowski** [yegor256/eo#9]
In Java, to initialize a field with the value from ctor parameter, we have to write a lot of code.
Your proposal from Readme is slightly less verbose and better:

    String isbn;
    String title;
    Book(ISBN i, String t):
      isbn(i),
      title(t);

..but in my opinion, we can do it even more elegant by being inspired with Kotlin. Take a look, here is how we are creating a class `Person` with one private field called `firstName` and one ctor, which takes a `firstName` argument and assigns its value to field:

    class Person(firstName: String) {
    }

More: https://kotlinlang.org/docs/reference/classes.html

**Comment by yegor256** [comment]
@pchmielowski I think we should avoid any code in constructors. They have to be code-free. That's why I don't see any reason for that `{}` brackets. Kotlin notation looks too complex, don't you think?

**Comment by mdbs99** [comment]
@pchmielowski 
That was my idea too, but with a little different syntax, see [here](https://github.com/yegor256/eo/issues/6#issue-188812018)

**Comment by yegor256** [comment]
@mdbs99 I think I don't like this approach. I think we have to make constructors look _obviously_ different from methods. They must not have any code. They only have to encapsulate. Just like it's done in C++. But in C++ you can also write code. In EO there will only be encapsulation. Make sense?

**Comment by mdbs99** [comment]
@yegor256 yes, make sense.
But in my example #6 I wrote this syntax about constructor:
`constructor (n: String) { var name = n }`

There is only encapsulation. Besides that, the ctor has a different syntax, using a new keyword.

**Comment by pchmielowski** [comment]
@yegor256 OK, so I'll change my proposal by removing `{ }` part:

    class Person(firstName: String)

What I mean is that in 99% of cases our (primary) ctors are assigning the value of parameter to the field of similar or the same name. 
So, the point of my solution was to **make the primary ctor params declaration, automatically the fields declarations**.
(Of course, like in Kotlin, we can let the programmers also declaring ctor params and fields independently.)

**Comment by mdbs99** [comment]
We'll need the option to introduce code.
Sometimes we can initialize an attribute ourselves, not only using arguments.

**Comment by yegor256** [comment]
@mdbs99 good point, but I disagree. Can you give an example where we really need to have code in ctor? And I will show you how this code may/should/must be replaced by something else. In my opinion ctors must _always_ be code-free.

**Comment by mdbs99** [comment]
@yegor256, for example, we can have 3 ctors:
1) primary: ctor1(arg1, arg2, arg3)
2) secondary: ctor1(arg1, arg2)
3) secondary: ctor1(arg1)

If we use the ctor 3, we can use a default value for initialize the ctor 2 and then it will call the ctor 1.
Make sense?

**Comment by yegor256** [comment]
@mdbs99 but that "default value" is not the code, it's just a call to another ctor. So, here is an example:

```
object Text("Hello"):
  String @body
  String @encoding
  Text(String body, String encoding):
    @body= body
    @encoding= encoding
  Text(String body):
    Text: body, "UTF-8"
```

WDYT?

**Comment by yegor256** [comment]
@mdbs99 and you can make it even more complex:

```
object Text("Hello"):
  String @body
  String @encoding
  Text(String body, String encoding):
    @body= body
    @encoding= encoding
  Text(String body):
    Text: 
      body,
      concat:
        string: "UTF"
        string: "-"
        string: "8"
```

**Comment by pchmielowski** [comment]
BTW, let me recall the original question on this topic on your last example. Doesn't it look more clear?

```
object Text("Hello"):
  Text(String body, String encoding) // primary
  Text(String body):
    Text: 
      body,
      concat:
        string: "UTF"
        string: "-"
        string: "8"
```
As we have two params in primary ctor, there is no need to explicitly define fields and assign them the values.

**Comment by mdbs99** [comment]
@yegor256 I mean this (see the last line)
```
object Text("Hello"):
  String @body
  String @encoding
  Text(String body, String encoding):
    @body= body
    @encoding= encoding
  Text(String body):
    Text: body, object UTF8String
```
We can use default values (strings, number, etc) but and what about use real objects calling their ctors?

**Comment by yegor256** [comment]
@pchmielowski I've made a lot of changes to the README, please take a look. I think this ticket can be closed

**Comment by pchmielowski** [comment]
@yegor256 No, because the original topic was not discussed.
The code in ctors was discussed (btw. I agree, that they should be code free), but the original point of this topic was about implicit definitions of object's fields/properties.

**Comment by yegor256** [comment]
@pchmielowski I think that this idea won't be necessary after #61 I think that we don't need to initialize anything explicitly. Every object will just automatically have a primary constructor that initializes all encapsulated attributes and that's it.

**Comment by pchmielowski** [comment]
@yegor256 I agree. I'm closing the issue.
