### ISSUE TITLE
Qulice and redundant Javadoc comments

### ISSUE THREAD

**Issue by pa9ey** [yegor256/eo#99]
I have a bunch of questions about Javadoc comments.

1. Should the licensing comments be Javadoc comments or just block comments? (IntelliJ says they're just dangling when they're Javadoc comments...)
2. What are the Javadoc comments used for?
3. ~~Can I know that Qulice is going to complain before my pull request tries to merge?~~ (`mvn clean install -Pqulice` does the trick)
4. What's the point of knowing the author of a class? This can be found out from version control but it's also probably irrelevant once enough changes have happened.
5. How do the `@version` and `@since` things help?
6. Do all classes, methods, attributes really need Javadoc comments?

What's the point of...
```
    /**
     * Method name.
     */
```
...if it basically just repeats the code?
```
public final class Method {
    private final String name;
```

**Comment by pa9ey** [comment]
Since nobody's biting I'll play devil's advocate... :)

The strict Javadoc comments are useful if you're writing and publishing an API. You would of course need to publish the docs somewhere for users of the API and then even seemingly redundant documentation would be needed for completeness and consistency.

And even if you're not publishing an API there are still people contributing to the code base, and aren't some of the classes and methods going to need more explanation than the code itself supplies?

**Comment by yegor256** [comment]
@pa9ey that's a long discussion) In a nutshell, we need discipline. That's what is important. Yes, very often that method JavaDoc blocks are pointless, but their mandatory presence makes code more disciplined. All other things you mentioned - too. More rules is better than less rules, I believe, in coding.

**Comment by pa9ey** [comment]
@yegor256 I'm all for discipline. :) It just seem redundant here and clutters up the code, making the files longer and uglier than they need to be. It too often doesn't add anything more that.

It seems to me that if have good naming and terse, spec-like, well-written tests (which I assume we're going to have anyway) then that's all the documentation you need (at least in the vast majority of cases - I know there are always exceptions).

**Comment by alex-semenyuk** [comment]
I think you answered on the own question I mean: 

> at least in the vast majority of cases - I know there are always exceptions

if we always add this stuff there will be no this exception cases. So people are lazy and it's good:), but how result they will not add this comments when it's really required.

**Comment by pa9ey** [comment]
@alex-semenyuk It doesn't answer the question for me at all. Why add lots of ugly, redundant, clutter just to trap a couple of cases where comments might be needed. Code review can trap those.

**Comment by alex-semenyuk** [comment]
IMO argue that code review that it is a procedure for trapping this. Even if read directly  'CODE' review not 'COMMENTS' review:) Also I think that 'qulice review' is more efficient that 'manual review', because person can miss something.

**Comment by pa9ey** [comment]
@alex-semenyuk We may be misunderstanding each other, or just coming from very different places. I don't know. But Qulice doesn't review anything other than the mere *presence* of a "comment". It might be a lie, it might be confusing, it might be gibberish, it might be a redundant waste of space. Only review can catch these things anyway, so we've gained nothing from Qulice.

**Comment by alex-semenyuk** [comment]
> I don't know. But Qulice doesn't review anything other than the mere presence of a "comment". The comment might be a complete lie, it might be confusing, it might be gibberish, it might be a redundant waste of space. Only review can catch these things anyway, so we've gained nothing from Qulice.

@pa9ey It's all true, of course, It might be but I don't see any objective reason specially write lie, gibberish in comments, from other side I see the objective reason why persons will not write it at all, even **it's really required/must be** - it's **laziness**, developers will think:"Why I should write it at all if another don't do that" and I think strict rules from Qulice avoid this thinking.
About waste of space, yes, but again I don't think that they size is so big/critical. 
Although again repeat that this is only my opinion.

**Comment by alexpanov** [comment]
>strict rules from Qulice avoid this thinking

In this case, all that's avoided is *not* wasting bytes with a templated, meaningless comment.

**Comment by pa9ey** [comment]
I've numbered the questions in the original comment because (even if we accept the discipline-for-discipline's-sake argument) most of the questions haven't really been addressed. e.g. 1, 2, 4 & 5.

**Comment by yegor256** [comment]
@pa9ey it's very important to keep all tickets in "as a bug" format, check this out: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html In this case, you're asking multiple questions, but not stating what the problems are. That's why this discussion it going nowhere. I would recommend you close this one and submit a few smaller tickets, which will explain what our bugs are and what solutions you would recommend.

**Comment by pa9ey** [comment]
@yegor256 You're right. I'll tidy it up later today.

**Comment by pa9ey** [comment]
@yegor256 @alex-semenyuk @alexpanov @pchmielowski @g4s8 
See #107 #108 #109.

I will close this issue shortly.
